name: mango
description: mango is a cat.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # http请求 https://github.com/flutterchina/dio
  dio: ^3.0.10
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^4.3.2+3
  # Stream扩展 https://github.com/ReactiveX/rxdart
  rxdart: ^0.25.0
  # 路由 https://github.com/theyakka/fluro
  fluro: ^1.7.8
  # json_serializable的反序列化注解
  json_annotation: ^2.3.0
  # 轻量化存储库 key-value模式 用来存储用户信息、缓存信息 复杂的数据存储请使用sqflite
  shared_preferences: ^0.5.12+4
  # 轻量化存储库 库-表模式 用来存储复杂数据，如离线模式的存储
  # sqflite: ^1.1.6+3
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.2
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^1.0.7
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.1+1
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.7.10
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.5.0 
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.2.1
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.3.3
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^5.0.0
  # 加密解密 https://github.com/dart-lang/crypto
  crypto: ^2.1.5
  # 图表 https://github.com/google/charts
  charts_flutter: ^0.9.0
  # 加载动画
  loading_indicator_view: ^1.1.0
  # 极光推送
  jpush_flutter: ^0.6.1
  barcode_scan:
    git:
      url: https://github.com/simplezhli/flutter_barcode_reader.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  # json自动生成model https://github.com/flutterchina/json_model
  json_model: ^0.0.2
  build_runner: ^1.0.0 
  json_serializable: ^2.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/state/
    - assets/images/login/
    - assets/images/user/

  fonts:
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
